### ISSUE TITLE
JPG

### ISSUE THREAD

**Issue by josehg1979** [leechy/imgsupport#3]
Since I'm serving photographs, I would like to use jpg instead of svg, How i should do it?

**Comment by leechy** [comment]
Sorry for the late response :-((

If you want to check AVIF, WebP, or JPEG, then the CSS should be like this:

```css
html.avif .your-image {
  background-image: url('your-image.avif');
}

/* since browsers that are supporting AVIF are also supporting WebP,
   we have to exclude the newer ones from loading the WebP */
html.webp.notavif .your-image {
  background-image: url('your-image.avif');
}

/* Same for the JPEG — only for browsers that are not supporting AVIF and WebP
   we don't have a special class for JPEG, since all browsers are supporting it,
   but we can check that the browser is not supporting superior file formats */
html.notwebp.notavif .your-image {
  background-image: url('your-image.avif');
}
```

HTH
